* About this Software

clj-span is an implementation of the Service Path Attribution Networks
(Springer LNCS 2010 - Johnson et al.) framework for Ecosystem Service
Assessment.

Using clj-span, you can run a collection of parameterizable SPAN flow
simulation models (line-of-sight, proximity, carbon, flood-water,
surface-water, sediment, coastal-storm-protection, and
subsistence-fisheries) and visualize their results as map outputs.

Copyright Gary W. Johnson (gjohnson@green-compass.org) 2009-2013

* Usage

To run clj-span, you will need:

1) Sun's JDK 1.7+
2) clj-span-standalone.jar (contains clojure-1.5.1)

Then simply place clj-span-standalone.jar on your classpath and fire
up your JVM as follows:

#+begin_src sh
java -cp clj-span-standalone.jar clj_span.commandline \
     -config-file        <filepath>                 \
     -source-layer       <filepath>                 \
     -sink-layer         <filepath>                 \
     -use-layer          <filepath>                 \
     -flow-layers        <filepath>                 \
     -source-threshold   <double>                   \
     -sink-threshold     <double>                   \
     -use-threshold      <double>                   \
     -trans-threshold    <double>                   \
     -cell-width         <double>                   \
     -cell-height        <double>                   \
     -rv-max-states      <integer>                  \
     -downscaling-factor <number>                   \
     -source-type        <finite|infinite>          \
     -sink-type          <finite|infinite>          \
     -use-type           <finite|infinite>          \
     -benefit-type       <rival|non-rival>          \
     -value-type         <numbers|varprop|randvars> \
     -animation?         <true|false>               \
     -flow-model         <line-of-sight|proximity|carbon|flood-water|surface-water|sediment|coastal-storm-protection|subsistence-fisheries>
#+end_src

* License

clj-span is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

clj-span is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with clj-span.  If not, see <http://www.gnu.org/licenses/>.
